import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarPlus, ClipboardCheck, Pencil, Plus, Users, Video } from "lucide-react";
import { AssessmentActions, ScoreAndCertificateActions } from "@/components/assessment-actions";
import { RegistrationStatusButton } from "@/components/registration-actions";
import { formatCurrency, formatDate, formatDateRange, type RegistrationStatus } from "@/lib/domain";
import { getTrainingById, listRegistrations } from "@/lib/repository";
import { addTrainingSessionAction, assignFacilitatorAction, publishTrainingAction } from "@/lib/actions";
import { getCurrentUser } from "@/lib/session";
import { canFacilitateTraining } from "@/lib/training-management";

export const dynamic = "force-dynamic";

interface AdminTrainingPageProps { params: Promise<{ id: string }> }

export default async function AdminTrainingPage({ params }: AdminTrainingPageProps) {
  const id = Number((await params).id);
  if (!Number.isInteger(id)) notFound();
  const training = getTrainingById(id);
  if (!training) notFound();
  const user = await getCurrentUser();
  const registrations = listRegistrations({ trainingId: id });
  const totalJp = training.totalJp;
  const assignedFacilitators = user?.role === "FACILITATOR" ? canFacilitateTraining(id, user.id) : true;
  return (
    <>
      <div className="content-head"><div><Link href="/dashboard/diklat" className="form-hint"><ArrowLeft size={12} style={{ verticalAlign: "-2px" }} /> Semua diklat</Link><div className="eyebrow" style={{ marginTop: 14 }}>{training.category} · {training.status}</div><h1 className="display">{training.title}</h1><p>{training.subtitle}</p></div><Link className="button secondary" href={`/diklat/${training.slug}`} target="_blank"><Video size={14} /> Lihat halaman publik</Link></div>
      <div className="stat-grid"><div className="stat-card"><p>Total JP</p><strong>{totalJp}</strong><small>{training.sessions.length} sesi</small></div><div className="stat-card"><p>Tersedia</p><strong>{Math.max(0, training.quota - registrations.filter((item) => item.status !== "REJECTED" && item.status !== "CANCELLED").length)}</strong><small>dari {training.quota} kuota</small></div><div className="stat-card"><p>Biaya</p><strong style={{ fontSize: 30 }}>{training.price ? formatCurrency(training.price) : "Gratis"}</strong><small>{training.method === "ONLINE" ? "Online" : "Hybrid/offline"}</small></div><div className="stat-card"><p>Nilai minimum</p><strong>{training.passScore}</strong><small>JP minimum {training.minimumAttendanceJp}</small></div></div>
      {training.status === "DRAFT" ? <section className="panel" style={{ marginTop: 18, padding: 22 }}><div className="panel-head" style={{ padding: 0, border: 0 }}><h2>Draft belum tayang</h2><span className="badge orange">Perlu sesi</span></div><p className="muted" style={{ margin: "15px 0", fontSize: 12, lineHeight: 1.6 }}>Tambahkan sesi dan JP terlebih dahulu. Setelah total JP valid, terbitkan diklat agar muncul di katalog dan menerima pendaftaran.</p><div className="form-actions"><form action={addTrainingSessionAction} className="form-actions"><input type="hidden" name="trainingId" value={training.id} /><input className="form-field" name="title" placeholder="Judul sesi" required /><input className="form-field" name="sessionDate" type="date" required /><input className="form-field" name="startTime" type="time" required /><input className="form-field" name="endTime" type="time" required /><input className="form-field" name="platform" defaultValue="ZOOM" /><input className="form-field" name="meetingUrl" type="url" placeholder="Link meeting (opsional)" /><input className="form-field" name="jp" type="number" min="1" defaultValue="8" required /><button className="button small secondary" type="submit"><CalendarPlus size={13} /> Tambah sesi</button></form><form action={publishTrainingAction}><input type="hidden" name="trainingId" value={training.id} /><button className="button small lime" type="submit"><Plus size={13} /> Terbitkan diklat</button></form></div></section> : null}
      {user?.role === "ADMIN" || user?.role === "SUPER_ADMIN" ? <div className="panel" style={{ marginTop: 18, padding: 18 }}><form action={assignFacilitatorAction} className="form-actions"><input type="hidden" name="trainingId" value={training.id} /><input className="form-field" name="facilitatorId" type="number" min="1" placeholder="ID fasilitator" required /><button className="button small ghost" type="submit">Tugaskan fasilitator</button></form></div> : null}
      <div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Sesi & materi</h2><span className="form-hint">Total {totalJp} JP</span></div><div className="panel-body"><div className="session-list">{training.sessions.length ? training.sessions.map((session, index) => <div className="session-row" key={session.id}><span className="session-number">{String(index + 1).padStart(2, "0")}</span><div><h3>{session.title}</h3><p>{formatDate(session.sessionDate)} · {session.startTime}–{session.endTime} · {session.platform}</p>{session.meetingUrl ? <a href={session.meetingUrl} target="_blank" rel="noreferrer" className="form-hint" style={{ color: "var(--blue)" }}>Buka link meeting ↗</a> : null}</div><span className="session-jp">{session.jp} JP</span></div>) : <p className="muted" style={{ fontSize: 12 }}>Belum ada sesi. Tambahkan sesi agar JP dan absensi dapat tercatat.</p>}</div></div></section><section className="panel" style={{ background: "var(--ink)", color: "var(--surface)" }}><div className="panel-head" style={{ borderColor: "rgba(255,255,255,.16)" }}><h2>Detail program</h2><Pencil size={15} style={{ color: "var(--lime)" }} /></div><div className="panel-body"><p style={{ color: "rgba(255,254,250,.72)", fontSize: 13, lineHeight: 1.6 }}>{training.description}</p><div className="sidebar-list" style={{ marginTop: 25, color: "var(--surface)" }}><div style={{ borderColor: "rgba(255,255,255,.16)" }}><dt style={{ color: "rgba(255,254,250,.58)" }}>Jadwal</dt><dd>{formatDateRange(training.startsAt, training.endsAt)}</dd></div><div style={{ borderColor: "rgba(255,255,255,.16)" }}><dt style={{ color: "rgba(255,255,250,.58)" }}>Fasilitator</dt><dd>{training.facilitator}</dd></div><div style={{ borderColor: "rgba(255,255,255,.16)" }}><dt style={{ color: "rgba(255,254,250,.58)" }}>Pendaftaran</dt><dd>{formatDate(training.registrationDeadline)}</dd></div><div style={{ borderColor: "rgba(255,255,255,.16)" }}><dt style={{ color: "rgba(255,255,250,.58)" }}>Sertifikat</dt><dd>{training.certificateLabel}</dd></div></div></div></section></div>
      <section className="panel" style={{ marginTop: 18 }}><div className="panel-head"><h2>Peserta & penilaian</h2><span className="badge blue"><Users size={12} style={{ verticalAlign: "-2px" }} /> {registrations.length} peserta</span></div><div className="table-wrap"><table><thead><tr><th>Peserta</th><th>Status</th><th>JP</th><th>Nilai</th><th>Hasil</th><th>Admin</th></tr></thead><tbody>{registrations.length ? registrations.map((registration) => <tr key={registration.id}><td><strong>{registration.participant_name}</strong><br /><span className="muted">{registration.participant_email}</span></td><td><span className={`badge ${registration.status === "COMPLETED" ? "green" : registration.status === "REJECTED" ? "red" : registration.status === "PENDING" ? "orange" : "blue"}`}>{registration.status}</span></td><td>{Math.round(registration.earned_jp)} / {registration.total_jp} JP</td><td>{registration.final_score != null ? registration.final_score : "—"}</td><td>{registration.result_status !== "PENDING" ? <span className={`badge ${registration.result_status === "PASSED" ? "green" : "red"}`}>{registration.result_status === "PASSED" ? "Lulus" : "Belum lulus"}</span> : <span className="muted">Menunggu</span>}</td><td><div className="form-actions"><RegistrationStatusButton registrationId={registration.id} status={registration.status as RegistrationStatus} /><ScoreAndCertificateActions registrationId={registration.id} hasResult={registration.result_status !== "PENDING"} hasCertificate={false} />{assignedFacilitators ? training.sessions.map((session) => <AssessmentActions key={session.id} registrationId={registration.id} sessionId={session.id} />) : null}</div></td></tr>) : <tr><td colSpan={6}><div className="empty-state"><ClipboardCheck size={24} style={{ color: "var(--blue)" }} /><h3>Belum ada peserta</h3><p>Bagikan halaman publik diklat agar peserta dapat mendaftar.</p></div></td></tr>}</tbody></table></div></section>
    </>
  );
}
